# -*- coding: utf-8 -*-
"""2119167SWE6204.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qPiQyMSYNBql5fulC-vdQusYX5XcOyKz
"""

# Install the Simple Transformers library
!pip install --upgrade simpletransformers

import logging
import random
import json
from simpletransformers.question_answering import QuestionAnsweringModel, QuestionAnsweringArgs

#Setting up logging to control the output of logs
logging.basicConfig(level=logging.INFO)
transformers_logger = logging.getLogger("transformers")
transformers_logger.setLevel(logging.WARNING)

# Define model arguments
model_args = QuestionAnsweringArgs()
model_args.n_best_size = 1  # Return only best answer from the model

# Initialize the model
model = QuestionAnsweringModel(
    "bert",
    "bert-base-uncased",
    args=model_args,
    use_cuda=True  # I have set it to false for now to use GPU, if true, uses CUDA-enabled GPU
)

# Function to load data from JSON files
def load_data(filename):
    with open(filename, 'r') as file:
        return json.load(file)["data"]



# Print the current working directory to help locate files if needed
import os
print(os.getcwd())

# Load the complete dataset
data = load_data('/content/Q&A_Dataset.json')


# Shuffle your data to ensure random distribution
random.shuffle(data)

# Calculate the number of questions to define training and validation set sizes
num_questions = len(data)
train_end = int(num_questions * 0.8)
val_end = train_end + int(num_questions * 0.1)



# Split the data into training, validation, and test sets
train_data = data[:train_end]
val_data = data[train_end:val_end]
test_data = data[val_end:]

# Function to save data to a file
def save_data(dataset, filename):
    with open(filename, 'w') as file:
        json.dump({"data": dataset}, file, indent=4)

# Save the split to separate files
save_data(train_data, '/content/Q&A_Dataset_train.json')
save_data(val_data, '/content/Q&A_Dataset_validation.json')
save_data(test_data, '/content/Q&A_Dataset_test.json')

# Train the model with the loaded datasets
model.train_model(train_data, eval_data=val_data)

# Install the transformers library
#!pip install transformers


# Load the test data from the saved JSON file
def load_data(filename):
    with open(filename, 'r') as file:
        data = json.load(file)
    return data['data']

test_data = load_data('/content/Q&A_Dataset_test.json')

# Correctly format the data for Simple Transformers
formatted_test_data = []
for entry in test_data:
    context = entry["context"]
    for qa in entry["qas"]:
        formatted_test_data.append({
            "context": context,
            "qas": [qa]
        })

# Load the trained model from the specified checkpoint
model = QuestionAnsweringModel(
    "bert",
    "outputs/checkpoint-9-epoch-1",  # Adjust this to the path where your trained model is saved
    use_cuda=True
)

# Generate predictions
predictions = model.predict(formatted_test_data)


# Extract answers and probabilities from the tuple
answer_predictions, probability_predictions = predictions

# Print answers along with their corresponding probabilities
for answer, probability in zip(answer_predictions, probability_predictions):
    print(f"ID: {answer['id']}")
    print(f"Answer: {answer['answer'][0]}")  # Assuming there is always at least one answer
    print(f"Probability: {probability['probability'][0]}")  # Assuming there is always one probability
    print()  # Adds a blank line between each prediction for better readability